### ISSUE TITLE
cmake custom command copying svg causes a problem

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/Test-FMUs#1]
I had to comment out the following lines in the global CMakeLists.txt in order to successfully build the project. 

`add_custom_command(TARGET ${TARGET_NAME} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy
  "${CMAKE_CURRENT_SOURCE_DIR}/${MODEL_NAME}/${MODEL_NAME}_ref.svg"
  "${FMU_BUILD_DIR}/documentation/${MODEL_NAME}_ref.svg"
)`

What I did to build the project is: 

1. navigate to my Tests-FMUs cloned root directory
2. mkdir build && cd build
3. cmake -G "Unix Makefiles" .. 
4. make all

The error is: 
`$ make all
Scanning dependencies of target BouncingBall
[  3%] Building C object CMakeFiles/BouncingBall.dir/BouncingBall/model.c.obj
[  6%] Building C object CMakeFiles/BouncingBall.dir/src/fmi2.c.obj
C:/SOMEWHERE/Test-FMUs/src/fmi2.c: In Funktion »fmi2Instantiate«:
C:/SOMEWHERE/Test-FMUs/src/fmi2.c:273:18: Warnung: Zuweisung von inkompatiblem Zeigertyp [-Wincompatible-pointer-types]
     comp->logger = functions->logger;
                  ^
C:/SOMEWHERE/Test-FMUs/src/fmi2.c:276:24: Warnung: Zuweisung von inkompatiblem Zeigertyp [-Wincompatible-pointer-types]
     comp->stepFinished = functions->stepFinished;
                        ^
[ 10%] Building C object CMakeFiles/BouncingBall.dir/src/euler.c.obj
[ 13%] Building C object CMakeFiles/BouncingBall.dir/src/slave.c.obj
[ 16%] Linking C shared library temp/BouncingBall/binaries/win64/BouncingBall.dll
Error copying file "C:/SOMEWHERE/Test-FMUs/BouncingBall/BouncingBall_ref.svg" to "temp/BouncingBall/documentation/BouncingBall_ref.svg".
make[2]: *** [CMakeFiles/BouncingBall.dir/build.make:177: temp/BouncingBall/binaries/win64/BouncingBall.dll] Fehler 1
make[2]: *** Datei „temp/BouncingBall/binaries/win64/BouncingBall.dll“ wird gelöscht
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/BouncingBall.dir/all] Fehler 2
make: *** [Makefile:84: all] Fehler 2
`

hoping this may not be due to some problem on my side. 
My plattform is Windows 7, Using cygwing and also using the cmake configurator + eclipse
Thanks!

**Comment by t-sommer** [comment]
I've added the missing SVGs. Thanks for your help!
