### ISSUE TITLE
fmi1.c: fmiInitialize does not set eventInfo

### ISSUE THREAD

**Issue by StefanOltean** [CATIA-Systems/Test-FMUs#3]
Hi,

We believe that `fmiInitialize` in fmi1.c:557 should set `eventInfo` (similar to how it is done in `fmiEventUpdate`). Not doing so limits the outputed information from the FMU during intialization. 

Best regards,
Stefan
QTronic GmbH

**Comment by t-sommer** [comment]
Can you make a PR with the proposed change?

**Comment by t-sommer** [comment]
Solved with 904bc97870d0d58e2a4ea105bdddd4fbec9ca27a and b41b343c2e4748dc146ea0e2b0f8b0f62fa3dc56
